replicaCount: 1

image:
  repository: 424579921836.dkr.ecr.eu-west-1.amazonaws.com/counter-service 
  pullPolicy: IfNotPresent
  tag: "v1.0.0"  

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources: {}
