apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "counter-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "counter-service.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "counter-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "counter-service.name" . }}
    spec:
      containers:
        - name: {{ include "counter-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
