apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "counter-service.fullname" . }}
  labels:
    app: {{ include "counter-service.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: "" # automatically generate hostname by AWS
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "counter-service.fullname" . }}
                port:
                  number: 80