apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "counter-service.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "counter-service.name" . }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
